config/routes.rb
Rails.application.routes.draw do

  get 'votes/create'
  get 'votes/destroy'
  root to: "questions#index"
  
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"
  
  get "signup", to: "users#new"

  resources :questions, only: [:index, :show, :new, :create, :destroy] do
    collection do
      get :finish
      get :all
    end
  end
  
  resources :users, only: [:create]
  resources :choices, only: [:show, :new, :create, :destroy]
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/choice.rb
class Choice < ApplicationRecord
  validates :content, length: { maximum: 30 }
  validates_presence_of :question

  belongs_to :question
  has_many :votes
  has_many :survey, through: :votes, source: :question
end

app/models/question.rb
class Question < ApplicationRecord
  validates :content, presence: true, length: { maximum: 255 }
  validates :status, inclusion: { in: [true, false] }
  
  belongs_to :user
  has_many :choices, dependent: :destroy
  has_many :votes
  has_many :answers, through: :votes, source: :user
  has_many :survey, through: :votes, source: :choice
  
  accepts_nested_attributes_for :choices
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 }, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }, uniqueness: { case_sensitive: false }
  has_secure_password
  
  has_many :questions
  has_many :votes
  has_many :answers, through: :votes, source: :question  
  
  def vote(choice)
    self.votes.find_or_create_by(user_id: @current_user, question_id: @question, choice_id: @choice)
  end

  def vote?(user_id: @current_user, question_id: @question, choice_id: @choice)
    self.votes.include?(user_id: @current_user, question_id: @question, choice_id: @choice)
  end
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :user
  belongs_to :question
  belongs_to :choice
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
  
  private
  
  def require_user_logged_in
    unless logged_in?
      redirect_to login_url
    end
  end
end

app/controllers/choices_controller.rb
class ChoicesController < ApplicationController

  def new
    @choice = Choice.new
  end
  
  def create
    @choice = @question.choices.build(choice_params)
    @choice.save
    redirect_to "/"
  end

  def destroy
  end
  
  
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
   before_action :require_user_logged_in
  
  def index
    @questions = Question.all
    @question = Question.new
  end

  def show
    @question = Question.find(params[:id])
    @choices = @question.choices
  end

  def new
    @question = Question.new
    4.times { @question.choices.build }
  end

  def create
    @question = current_user.questions.build(question_params)

    if @question.save
      flash[:success] = "アンケートを投稿しました。"
      redirect_to "/"
    else
      flash.now[:danger] = "アンケートの投稿に失敗しました。"
      render :new
    end
  end

  def destroy
    @question = Question.find(params[:id])
    @question.destroy
    redirect_to "/"
  end
  
  private
  def question_params
    params.require(:question).permit(:content, choices_attributes: :content)
  end
  
 

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = "ログインに成功しました。"
      redirect_to "/"
    else
      flash.now[:danger] = "ログインに失敗しました。"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "ログアウトしました。"
    redirect_to login_url
  end
  
  private
  
  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      session[:user_id] = @user.id
      return true
    else
      return false
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    
    if @user.save
      flash[:success] = "ユーザーを登録しました。"
      redirect_to "/"
    else
      flash.now[:danger] = "ユーザーの登録に失敗しました。"
      render :new
    end
  end
 
  private
   
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  def create
    current_user.vote(params[:vote_id])
    flash[:success] = '投票しました'
    redirect_to question_path(current_user)
  end

  def destroy
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/choices_helper.rb
module ChoicesHelper
end

app/helpers/create_helper.rb
module CreateHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  def logged_in?
    !!current_user
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/create/destroy.html.erb
<h1>Create#destroy</h1>
<p>Find me in app/views/create/destroy.html.erb</p>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<header class="mb-4">
  <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
    <a class="navbar-brand" href="/">Anketoo</a>
    <button class="navbar-toggler" type="button" deta-toggle="collapse" deta-target="#navbarSupportedContent">
      <span class="navbar-toggle-icon"></span>
    </button>
    
    <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
      <ul class="navbar-nav">
        <% if logged_in? %>
          <li class="nav-item"><%= link_to "アンケる！", new_question_path, class: 'btn btn-primary' %></li>
          <li class="nav-item"><%= link_to "Logout", logout_path, method: :delete, class: "btn btn-danger" %></li>
      </ul>
      <% else %>
        <li class="nav-item"><%= link_to "Signup", signup_path, class: "nav-link" %></li>
        <li class="nav-item"><%= link_to "Login", login_path, class: "nav-link" %></li>
      <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=divice-width, initial-scale=1, shrink-to-fit=no">
    <title>Anketoo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.7.2/js/all.js"></script>
  </head>

  <body>
    <%= render 'layouts/navbar' %>

    <div class="container">
      <%= render 'layouts/flash_messages' %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/questions/all.html.erb
<h1>アンケート一覧</h1>

<div class="row">
  <div class="col-sm-12">
    <ul class="nav nav-tabs nav-justified mb-3">
      <li class="nav-item"><a href="<%= questions_path(@question) %>" class="nav-link <%= "active" if current_page?(questions_path(@question)) %>">投票中</a></li>
      <li class="nav-item"><a href="<%= finish_questions_path(@question) %>" class="nav-link <%= 'active' if current_page?(finish_questions_path(@question)) %>">投票終了</a></li>
      <li class="nav-item"><a href="<%= all_questions_path(@question) %>" class="nav-link <%= 'active' if current_page?(all_questions_path(@question)) %>">全て</a></li>
    </ul>
    
    
  </div>
</div>

app/views/questions/finish.html.erb
<h1>アンケート一覧</h1>

<div class="row">
  <div class="col-sm-12">
    <ul class="nav nav-tabs nav-justified mb-3">
      <li class="nav-item"><a href="<%= questions_path(@question) %>" class="nav-link <%= "active" if current_page?(questions_path(@question)) %>">投票中</a></li>
      <li class="nav-item"><a href="<%= finish_questions_path(@question) %>" class="nav-link <%= 'active' if current_page?(finish_questions_path(@question)) %>">投票終了</a></li>
      <li class="nav-item"><a href="<%= all_questions_path(@question) %>" class="nav-link <%= 'active' if current_page?(all_questions_path(@question)) %>">全て</a></li>
    </ul>
    
    
  </div>
</div>

app/views/questions/index.html.erb
<h1>アンケート一覧</h1>

<div class="row">
  <div class="col-sm-12">
    <ul class="nav nav-tabs nav-justified mb-3">
      <li class="nav-item"><a href="<%= questions_path(@question) %>" class="nav-link <%= "active" if current_page?(questions_path(@question)) %>">投票中</a></li>
      <li class="nav-item"><a href="<%= finish_questions_path(@question) %>" class="nav-link <%= 'active' if current_page?(finish_questions_path(@question)) %>">投票終了</a></li>
      <li class="nav-item"><a href="<%= all_questions_path(@question) %>" class="nav-link <%= 'active' if current_page?(all_questions_path(@question)) %>">全て</a></li>
    </ul>
    
    <% @questions.each do |question| %>
      <div class="alert alert-secondary" role="alert">
        <%= link_to question.content, question %>
      </div>
    <% end %>
  </div>
</div>

app/views/questions/new.html.erb
<h3><%= @current_user.name %></h3>

  <div class="row">
    <aside class="col-sm-10">
      <%= form_for @question do |f| %>
      <%= render "layouts/error_messages", model: f.object %>
      
        <%= f.label :"質問記入欄" %>
        <%= f.text_area :content, size: "60x10", class: "form-control" %>
        
        <%= f.fields_for :choices do |choice_fields| %>
          <%= choice_fields.label :"選択肢" %>
          <%= choice_fields.text_field :content, size: 60, class: "form-control" %>
  
        <% end %>
        
        <%= f.submit "投稿", class: "btn btn-primary" %>
      <% end %>
    </aside>
  </div>


<p>アンケート作成中・・・</p>

app/views/questions/show.html.erb
<h1>アンケート詳細</h1>

<% if current_user.vote? %>
  <div class="container">
      
    <div class="card">
      <div class="card-body">
        <p><%= @question.content %></p>
      </div>
    </div>
    
    
    <% @choices.each do |choice| %>
      <div class="alert alert-dark" role="alert">
        <p><%= choice.content %></p>
       </div>
    <% end %>
  </div>

<% else %>
  <div class="container">
      
    <div class="card">
      <div class="card-body">
        <p><%= @question.content %></p>
      </div>
    </div>
    
    
    <% @choices.each do |choice| %>
      <div class="alert alert-dark" role="alert">
        <%= button_to choice.content, {:controller => "votes", :action => "create"}, {:method => :get} %>
       </div>
    <% end %>
  </div>
<% end %>

<% if current_user == @question.user %>
  <%= link_to "Delete", @question, method: :delete, data: { confirm: "You sure?" }, class: "btn btn-danger btn-sm" %>
<% end %>

app/views/users/new.html.erb
<div class="text-center">
  <h1>Sign up</h1>
</div>

<div class="row">
  <div class="col-sm-6 offset-sm-3">
    
    <%= form_with(model: @user, local: true) do |f| %>
      <%= render "layouts/error_messages", model: f.object %>
      
      <div class="form-group">
        <%= f.label :name, "Name" %>
        <%= f.text_field :name, class: "form-control" %>
      </div>
      
      <div class="form-group">
        <%= f.label :email, "Email" %>
        <%= f.text_field :email, class: "form-control" %>
      </div>
      
      <div class="form-group">
        <%= f.label :password, "Password" %>
        <%= f.text_field :password, class: "form-control" %>
      </div>
      
      <div class="form-group">
        <%= f.label :password_confirmation, "Confirmation" %>
        <%= f.text_field :password_confirmation, class: "form-control" %>
      </div>
    
      <%= f.submit "Sign up", class: "btn btn-primary btn-block" %>
    <% end %>
  </div>
</div>

app/views/votes/create.html.erb
<h1>Votes#create</h1>
<p>Find me in app/views/votes/create.html.erb</p>

app/views/votes/destroy.html.erb
<h1>Votes#destroy</h1>
<p>Find me in app/views/votes/destroy.html.erb</p>